"""Application constants."""

APPLICATION_TYPES = {
    "Navy / Marine": {"icon": "⚓", "color": "#1a237e", "min_salt_spray": 3000, "min_adhesion": 8, "min_volume_solids": 65, "max_voc": 350},
    "Industry / Manufacturing": {"icon": "🏭", "color": "#ff6f00", "min_salt_spray": 1500, "min_adhesion": 6, "min_volume_solids": 60, "max_voc": 420},
    "Aviation / Aerospace": {"icon": "✈️", "color": "#0d47a1", "min_salt_spray": 2000, "min_adhesion": 10, "min_volume_solids": 70, "max_voc": 250},
    "Space / Satellite": {"icon": "🚀", "color": "#311b92", "min_salt_spray": 5000, "min_adhesion": 12, "min_volume_solids": 80, "max_voc": 100},
    "Building / Construction": {"icon": "🏗️", "color": "#795548", "min_salt_spray": 1000, "min_adhesion": 5, "min_volume_solids": 55, "max_voc": 420},
    "Automotive": {"icon": "🚗", "color": "#c62828", "min_salt_spray": 1000, "min_adhesion": 6, "min_volume_solids": 55, "max_voc": 350},
    "Oil & Gas": {"icon": "🛢️", "color": "#bf360c", "min_salt_spray": 3500, "min_adhesion": 9, "min_volume_solids": 70, "max_voc": 350},
}

# Translations - French and English
TRANSLATIONS = {
    "EN": {
        "title": "NanoCoatBuilder - Coating Formulation Software",
        "newForm": "NEW FORMULATION", "validate": "VALIDATE (100g)", "analyze": "FULL ANALYSIS",
        "save": "SAVE RECIPE", "savePdf": "EXPORT PDF", "saveJson": "EXPORT JSON",
        "compare": "COMPARE", "history": "HISTORY", "reset": "RESET",
        "addRow": "ADD", "removeRow": "REMOVE", "ingredient": "Ingredient",
        "weight": "Weight (g)", "totalWeight": "Total Weight",
        "errorNoIngredients": "No ingredients with weight > 0",
        "recipeSaved": "Recipe saved successfully", "analysisReady": "Click FULL ANALYSIS to view results",
        "selectIngredient": "Select Ingredient", "isoCompliance": "ISO Compliance",
        "violations": "Violations", "validationRules": "Validation Rules",
        "performance": "Predicted Performance", "references": "Recent Literature",
        "formulaName": "Formulation Name", "synthesisProtocol": "Synthesis Protocol",
        "characterization": "Characterization Techniques", "graphs": "Performance Graphs",
        "statusReady": "Ready - Add ingredients (target 100g)",
        "analysisResults": "Analysis Results", "formulationType": "Coating Type",
        "environment": "Environment", "application": "Application Sector",
        "criticalErrors": "CRITICAL ERRORS", "warnings": "WARNINGS", "information": "INFORMATION",
        "meetsRequirements": "Meets Requirements", "failsRequirements": "Fails Requirements",
        "historySaved": "Saved to history", "historyLoaded": "Loaded from history",
        "historyDeleted": "Deleted from history", "noHistory": "No saved formulations",
        "selectFirst": "Select an item first", "needTwoHistory": "Need 2 formulations to compare",
        "sameFormulation": "Select different formulations", "comparisonTitle": "Formulation Comparison",
        "loadFromHistory": "Load Selected", "deleteFromHistory": "Delete Selected",
        "selectFirstComparison": "Select first", "selectSecondComparison": "Select second",
        "importForm": "Import", "importSuccess": "Imported successfully",
        "importError": "Import error", "jsonExported": "JSON exported",
        "requirements": "Requirements", "resins": "Resins", "nanocomposites": "Nanocomposites",
        "pigments": "Pigments", "solvents": "Solvents", "additives": "Additives", "fillers": "Fillers",
        "validationPassed": "All validation rules passed!",
        "corrosionRate": "Corrosion Rate", "adhesion": "Adhesion", "saltSpray": "Salt Spray",
        "volumeSolids": "Volume Solids", "voc": "VOC", "costPerLitre": "Cost per Litre",
        "serviceLife": "Service Life", "hardness": "Hardness", "contactAngle": "Contact Angle",
        "materialPreparation": "MATERIAL PREPARATION", "nanoparticleDispersion": "NANOPARTICLE DISPERSION",
        "resinDissolution": "RESIN DISSOLUTION", "pigmentAddition": "PIGMENT AND FILLER ADDITION",
        "additiveIncorporation": "ADDITIVE INCORPORATION", "degassing": "DEGASSING",
        "applicationStep": "APPLICATION", "curingStep": "CURING", "qualityControl": "QUALITY CONTROL",
        "safetyNotes": "SAFETY NOTES", "equipmentNeeded": "EQUIPMENT NEEDED", "procedureSteps": "PROCEDURE STEPS",
        "characterizationTitle": "Characterization Techniques", "referencesTitle": "Recent Literature"
    },
    "FR": {
        "title": "NanoCoatBuilder - Logiciel de Formulation",
        "newForm": "NOUVELLE FORMULE", "validate": "VALIDER (100g)", "analyze": "ANALYSE COMPLÈTE",
        "save": "SAUVEGARDER", "savePdf": "EXPORTER PDF", "saveJson": "EXPORTER JSON",
        "compare": "COMPARER", "history": "HISTORIQUE", "reset": "RÉINITIALISER",
        "addRow": "AJOUTER", "removeRow": "SUPPRIMER", "ingredient": "Ingrédient",
        "weight": "Poids (g)", "totalWeight": "Poids Total",
        "errorNoIngredients": "Aucun ingrédient", "recipeSaved": "Recette sauvegardée",
        "analysisReady": "Cliquez ANALYSE pour voir résultats", "selectIngredient": "Choisir ingrédient",
        "isoCompliance": "Conformité ISO", "violations": "Violations",
        "validationRules": "Règles", "performance": "Performances", "references": "Références",
        "formulaName": "Nom formule", "synthesisProtocol": "Protocole", "characterization": "Caractérisation",
        "graphs": "Graphiques", "statusReady": "Prêt - Ajoutez ingrédients (cible 100g)",
        "analysisResults": "Résultats", "formulationType": "Type revêtement",
        "environment": "Environnement", "application": "Secteur application",
        "criticalErrors": "ERREURS CRITIQUES", "warnings": "AVERTISSEMENTS", "information": "INFORMATION",
        "meetsRequirements": "Répond aux exigences", "failsRequirements": "Ne répond pas",
        "historySaved": "Sauvegardé", "historyLoaded": "Chargé", "historyDeleted": "Supprimé",
        "noHistory": "Aucune formulation", "selectFirst": "Sélectionnez d'abord",
        "needTwoHistory": "Besoin de 2 formulations", "sameFormulation": "Choisissez différentes",
        "comparisonTitle": "Comparaison", "loadFromHistory": "Charger", "deleteFromHistory": "Supprimer",
        "selectFirstComparison": "Première", "selectSecondComparison": "Seconde",
        "importForm": "Importer", "importSuccess": "Importé avec succès",
        "importError": "Erreur d'import", "jsonExported": "JSON exporté",
        "requirements": "Exigences", "resins": "Résines", "nanocomposites": "Nanocomposites",
        "pigments": "Pigments", "solvents": "Solvants", "additives": "Additifs", "fillers": "Charges",
        "validationPassed": "Toutes les règles sont respectées!",
        "corrosionRate": "Taux de corrosion", "adhesion": "Adhérence", "saltSpray": "Brouillard salin",
        "volumeSolids": "Extrait sec", "voc": "COV", "costPerLitre": "Coût par litre",
        "serviceLife": "Durée de vie", "hardness": "Dureté", "contactAngle": "Angle de contact",
        "materialPreparation": "PRÉPARATION DES MATÉRIAUX", "nanoparticleDispersion": "DISPERSION DES NANOPARTICULES",
        "resinDissolution": "DISSOLUTION DE LA RÉSINE", "pigmentAddition": "AJOUT DES PIGMENTS ET CHARGES",
        "additiveIncorporation": "INCORPORATION DES ADDITIFS", "degassing": "DÉGAZAGE",
        "applicationStep": "APPLICATION", "curingStep": "CUISSON", "qualityControl": "CONTRÔLE QUALITÉ",
        "safetyNotes": "CONSIGNES DE SÉCURITÉ", "equipmentNeeded": "ÉQUIPEMENT NÉCESSAIRE", "procedureSteps": "ÉTAPES DE LA PROCÉDURE",
        "characterizationTitle": "Techniques de caractérisation", "referencesTitle": "Littérature récente"
    }
}